#!/bin/python

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(raw_input())

    for i in range(10):
        print(str(n) + " x " + str(i+1) + " = " + str(n*(i+1)))
        i = i+1
